[2022-01-03 08:02:01,368] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2022-01-03T08:01:00+00:00 [queued]>
[2022-01-03 08:02:01,384] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2022-01-03T08:01:00+00:00 [queued]>
[2022-01-03 08:02:01,384] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 08:02:01,384] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-03 08:02:01,385] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-01-03 08:02:01,393] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): echo_meet_date> on 2022-01-03T08:01:00+00:00
[2022-01-03 08:02:01,395] {standard_task_runner.py:52} INFO - Started process 1285434 to run task
[2022-01-03 08:02:01,400] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'echo_meet_date', '2022-01-03T08:01:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpesi3xxo1', '--error-file', '/tmp/tmpqs5pvdbn']
[2022-01-03 08:02:01,401] {standard_task_runner.py:77} INFO - Job 4: Subtask echo_meet_date
[2022-01-03 08:02:01,464] {logging_mixin.py:104} INFO - Running <TaskInstance: test.echo_meet_date 2022-01-03T08:01:00+00:00 [running]> on host airflowvm
[2022-01-03 08:02:01,538] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=echo_meet_date
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T08:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-03T08:01:00+00:00
[2022-01-03 08:02:01,539] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-01-03 08:02:01,540] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo 220104']
[2022-01-03 08:02:01,545] {subprocess.py:75} INFO - Output:
[2022-01-03 08:02:01,546] {subprocess.py:79} INFO - 220104
[2022-01-03 08:02:01,547] {subprocess.py:83} INFO - Command exited with return code 0
[2022-01-03 08:02:01,597] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=test, task_id=echo_meet_date, execution_date=20220103T080100, start_date=20220103T080201, end_date=20220103T080201
[2022-01-03 08:02:01,637] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-03 08:02:01,653] {local_task_job.py:151} INFO - Task exited with return code 0
