[2021-12-23 17:23:04,466] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2021-12-23T17:22:00+00:00 [queued]>
[2021-12-23 17:23:04,471] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2021-12-23T17:22:00+00:00 [queued]>
[2021-12-23 17:23:04,472] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-23 17:23:04,472] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-23 17:23:04,472] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-23 17:23:04,484] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): echo_meet_date> on 2021-12-23T17:22:00+00:00
[2021-12-23 17:23:04,486] {standard_task_runner.py:52} INFO - Started process 361612 to run task
[2021-12-23 17:23:04,491] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'echo_meet_date', '2021-12-23T17:22:00+00:00', '--job-id', '1799', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpjxwv77a_', '--error-file', '/tmp/tmp97jr2p5x']
[2021-12-23 17:23:04,492] {standard_task_runner.py:77} INFO - Job 1799: Subtask echo_meet_date
[2021-12-23 17:23:04,541] {logging_mixin.py:104} INFO - Running <TaskInstance: test.echo_meet_date 2021-12-23T17:22:00+00:00 [running]> on host airflowvm
[2021-12-23 17:23:04,661] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=echo_meet_date
AIRFLOW_CTX_EXECUTION_DATE=2021-12-23T17:22:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-23T17:22:00+00:00
[2021-12-23 17:23:04,662] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-23 17:23:04,662] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo 211228']
[2021-12-23 17:23:04,667] {subprocess.py:75} INFO - Output:
[2021-12-23 17:23:04,668] {subprocess.py:79} INFO - 211228
[2021-12-23 17:23:04,668] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-23 17:23:04,688] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=test, task_id=echo_meet_date, execution_date=20211223T172200, start_date=20211223T172304, end_date=20211223T172304
[2021-12-23 17:23:04,714] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-23 17:23:04,754] {local_task_job.py:151} INFO - Task exited with return code 0
