[2021-12-23 18:08:02,417] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2021-12-23T18:07:00+00:00 [queued]>
[2021-12-23 18:08:02,422] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2021-12-23T18:07:00+00:00 [queued]>
[2021-12-23 18:08:02,423] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-23 18:08:02,423] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-23 18:08:02,423] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-23 18:08:02,437] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): echo_meet_date> on 2021-12-23T18:07:00+00:00
[2021-12-23 18:08:02,438] {standard_task_runner.py:52} INFO - Started process 370778 to run task
[2021-12-23 18:08:02,444] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'echo_meet_date', '2021-12-23T18:07:00+00:00', '--job-id', '1850', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6c9x0fx0', '--error-file', '/tmp/tmp3bjnqx_v']
[2021-12-23 18:08:02,444] {standard_task_runner.py:77} INFO - Job 1850: Subtask echo_meet_date
[2021-12-23 18:08:02,490] {logging_mixin.py:104} INFO - Running <TaskInstance: test.echo_meet_date 2021-12-23T18:07:00+00:00 [running]> on host airflowvm
[2021-12-23 18:08:02,587] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=echo_meet_date
AIRFLOW_CTX_EXECUTION_DATE=2021-12-23T18:07:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-23T18:07:00+00:00
[2021-12-23 18:08:02,588] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-23 18:08:02,588] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo 211228']
[2021-12-23 18:08:02,592] {subprocess.py:75} INFO - Output:
[2021-12-23 18:08:02,593] {subprocess.py:79} INFO - 211228
[2021-12-23 18:08:02,594] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-23 18:08:02,613] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=test, task_id=echo_meet_date, execution_date=20211223T180700, start_date=20211223T180802, end_date=20211223T180802
[2021-12-23 18:08:02,630] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-23 18:08:02,655] {local_task_job.py:151} INFO - Task exited with return code 0
