[2021-12-23 18:11:02,501] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2021-12-23T18:10:00+00:00 [queued]>
[2021-12-23 18:11:02,507] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test.echo_meet_date 2021-12-23T18:10:00+00:00 [queued]>
[2021-12-23 18:11:02,507] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-23 18:11:02,507] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-23 18:11:02,508] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-23 18:11:02,520] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): echo_meet_date> on 2021-12-23T18:10:00+00:00
[2021-12-23 18:11:02,521] {standard_task_runner.py:52} INFO - Started process 371436 to run task
[2021-12-23 18:11:02,526] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'echo_meet_date', '2021-12-23T18:10:00+00:00', '--job-id', '1853', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpkp02c31a', '--error-file', '/tmp/tmp9um4qjig']
[2021-12-23 18:11:02,527] {standard_task_runner.py:77} INFO - Job 1853: Subtask echo_meet_date
[2021-12-23 18:11:02,586] {logging_mixin.py:104} INFO - Running <TaskInstance: test.echo_meet_date 2021-12-23T18:10:00+00:00 [running]> on host airflowvm
[2021-12-23 18:11:02,684] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=echo_meet_date
AIRFLOW_CTX_EXECUTION_DATE=2021-12-23T18:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-23T18:10:00+00:00
[2021-12-23 18:11:02,684] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-23 18:11:02,685] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo 211228']
[2021-12-23 18:11:02,689] {subprocess.py:75} INFO - Output:
[2021-12-23 18:11:02,690] {subprocess.py:79} INFO - 211228
[2021-12-23 18:11:02,690] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-23 18:11:02,707] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=test, task_id=echo_meet_date, execution_date=20211223T181000, start_date=20211223T181102, end_date=20211223T181102
[2021-12-23 18:11:02,726] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-23 18:11:02,741] {local_task_job.py:151} INFO - Task exited with return code 0
