[2021-12-20 06:04:47,197] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-20T05:50:00+00:00 [queued]>
[2021-12-20 06:04:47,201] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-20T05:50:00+00:00 [queued]>
[2021-12-20 06:04:47,202] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 06:04:47,202] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-12-20 06:04:47,202] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 06:04:47,210] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): git_add> on 2021-12-20T05:50:00+00:00
[2021-12-20 06:04:47,211] {standard_task_runner.py:52} INFO - Started process 4497 to run task
[2021-12-20 06:04:47,216] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'git_add', '2021-12-20T05:50:00+00:00', '--job-id', '265', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpuinlvu8q', '--error-file', '/tmp/tmpvvjh_ct2']
[2021-12-20 06:04:47,216] {standard_task_runner.py:77} INFO - Job 265: Subtask git_add
[2021-12-20 06:04:47,268] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.git_add 2021-12-20T05:50:00+00:00 [running]> on host airflowvm
[2021-12-20 06:04:47,429] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=git_add
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T05:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T05:50:00+00:00
[2021-12-20 06:04:47,430] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-20 06:04:47,430] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/AlgorithmStudy_211124/211221/ add rank.md']
[2021-12-20 06:04:47,441] {subprocess.py:75} INFO - Output:
[2021-12-20 06:04:47,445] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-20 06:04:47,463] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=git_add, execution_date=20211220T055000, start_date=20211220T060447, end_date=20211220T060447
[2021-12-20 06:04:47,492] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-20 06:04:47,509] {local_task_job.py:151} INFO - Task exited with return code 0
