[2021-12-20 06:21:25,564] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-20T06:10:00+00:00 [queued]>
[2021-12-20 06:21:25,570] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-20T06:10:00+00:00 [queued]>
[2021-12-20 06:21:25,570] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 06:21:25,570] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-20 06:21:25,570] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 06:21:25,577] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): pull_from_git> on 2021-12-20T06:10:00+00:00
[2021-12-20 06:21:25,578] {standard_task_runner.py:52} INFO - Started process 4436 to run task
[2021-12-20 06:21:25,583] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'pull_from_git', '2021-12-20T06:10:00+00:00', '--job-id', '278', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpbkjq4_0u', '--error-file', '/tmp/tmputgo7zmm']
[2021-12-20 06:21:25,583] {standard_task_runner.py:77} INFO - Job 278: Subtask pull_from_git
[2021-12-20 06:21:25,620] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.pull_from_git 2021-12-20T06:10:00+00:00 [running]> on host airflowvm
[2021-12-20 06:21:25,775] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=pull_from_git
AIRFLOW_CTX_EXECUTION_DATE=2021-12-20T06:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-20T06:10:00+00:00
[2021-12-20 06:21:25,775] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-20 06:21:25,775] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/AlgorithmStudy_211124 pull']
[2021-12-20 06:21:25,778] {subprocess.py:75} INFO - Output:
[2021-12-20 06:21:26,166] {subprocess.py:79} INFO - Already up to date.
[2021-12-20 06:21:26,167] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-20 06:21:26,188] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=pull_from_git, execution_date=20211220T061000, start_date=20211220T062125, end_date=20211220T062126
[2021-12-20 06:21:26,204] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-20 06:21:26,238] {local_task_job.py:151} INFO - Task exited with return code 0
